var TotalData = [
    {"name": "Food", "date": "1980", "value": "56"},
    {"name": "Clothing", "date": "1980", "value": "14.3"},
    {"name": "Household Facilities, Services", "date": "1980", "value": "9"},
    {"name": "Education,Culture and Services", "date": "1980", "value": "8.9"},
    {"name": "Residence", "date": "1980", "value": "4.7"},
    {"name": "Traffic and Communication", "date": "1980", "value": "3.6"},
    {"name": "Miscellanecus", "date": "1980", "value": "2.2"},
    {"name": "Medicines", "date": "1980", "value": "1.3"},
    {"name": "Food", "date": "1985", "value": "52.1"},
    {"name": "Clothing", "date": "1985", "value": "14.9"},
    {"name": "Household Facilities, Services", "date": "1985", "value": "13.2"},
    {"name": "Education,Culture and Services", "date": "1985", "value": "9.2"},
    {"name": "Residence", "date": "1985", "value": "4.4"},
    {"name": "Traffic and Communication", "date": "1985", "value": "3"},
    {"name": "Miscellanecus", "date": "1985", "value": "2.7"},
    {"name": "Medicines", "date": "1985", "value": "0.5"},
    {"name": "Food", "date": "1990", "value": "56.5"},
    {"name": "Education,Culture and Services", "date": "1990", "value": "11.9"},
    {"name": "Clothing", "date": "1990", "value": "10.7"},
    {"name": "Household Facilities, Services", "date": "1990", "value": "10.1"},
    {"name": "Residence", "date": "1990", "value": "4.7"},
    {"name": "Traffic and Communication", "date": "1990", "value": "3"},
    {"name": "Miscellanecus", "date": "1990", "value": "2.5"},
    {"name": "Medicines", "date": "1990", "value": "0.6"},
    {"name": "Food", "date": "1995", "value": "53.4"},
    {"name": "Household Facilities, Services", "date": "1995", "value": "10.8"},
    {"name": "Clothing", "date": "1995", "value": "9.6"},
    {"name": "Education,Culture and Services", "date": "1995", "value": "8.7"},
    {"name": "Residence", "date": "1995", "value": "6.8"},
    {"name": "Traffic and Communication", "date": "1995", "value": "5.5"},
    {"name": "Miscellanecus", "date": "1995", "value": "3.3"},
    {"name": "Medicines", "date": "1995", "value": "1.9"},
    {"name": "Food", "date": "1996", "value": "50.7"},
    {"name": "Education,Culture and Services", "date": "1996", "value": "12.2"},
    {"name": "Household Facilities, Services", "date": "1996", "value": "9.1"},
    {"name": "Clothing", "date": "1996", "value": "8.7"},
    {"name": "Traffic and Communication", "date": "1996", "value": "7.3"},
    {"name": "Residence", "date": "1996", "value": "6.2"},
    {"name": "Miscellanecus", "date": "1996", "value": "3.6"},
    {"name": "Medicines", "date": "1996", "value": "2.2"},
    {"name": "Food", "date": "1997", "value": "51.7"},
    {"name": "Education,Culture and Services", "date": "1997", "value": "12.1"},
    {"name": "Residence", "date": "1997", "value": "8.9"},
    {"name": "Clothing", "date": "1997", "value": "8.1"},
    {"name": "Household Facilities, Services", "date": "1997", "value": "7.7"},
    {"name": "Traffic and Communication", "date": "1997", "value": "5.8"},
    {"name": "Medicines", "date": "1997", "value": "2.9"},
    {"name": "Miscellanecus", "date": "1997", "value": "2.8"},
    {"name": "Food", "date": "1998", "value": "50.6"},
    {"name": "Education,Culture and Services", "date": "1998", "value": "13"},
    {"name": "Residence", "date": "1998", "value": "9.8"},
    {"name": "Clothing", "date": "1998", "value": "6.9"},
    {"name": "Household Facilities, Services", "date": "1998", "value": "6.6"},
    {"name": "Traffic and Communication", "date": "1998", "value": "5.9"},
    {"name": "Medicines", "date": "1998", "value": "3.8"},
    {"name": "Miscellanecus", "date": "1998", "value": "3.4"},
    {"name": "Food", "date": "1999", "value": "45.2"},
    {"name": "Education,Culture and Services", "date": "1999", "value": "13.3"},
    {"name": "Residence", "date": "1999", "value": "10.2"},
    {"name": "Household Facilities, Services", "date": "1999", "value": "9.3"},
    {"name": "Traffic and Communication", "date": "1999", "value": "7.1"},
    {"name": "Clothing", "date": "1999", "value": "6.7"},
    {"name": "Medicines", "date": "1999", "value": "4.2"},
    {"name": "Miscellanecus", "date": "1999", "value": "4"},
    {"name": "Food", "date": "2000", "value": "44.5"},
    {"name": "Education,Culture and Services", "date": "2000", "value": "14.5"},
    {"name": "Residence", "date": "2000", "value": "9"},
    {"name": "Traffic and Communication", "date": "2000", "value": "8.6"},
    {"name": "Household Facilities, Services", "date": "2000", "value": "7.7"},
    {"name": "Clothing", "date": "2000", "value": "6.4"},
    {"name": "Medicines", "date": "2000", "value": "5.6"},
    {"name": "Miscellanecus", "date": "2000", "value": "3.7"},
    {"name": "Food", "date": "2001", "value": "43.4"},
    {"name": "Education,Culture and Services", "date": "2001", "value": "15.2"},
    {"name": "Traffic and Communication", "date": "2001", "value": "10.3"},
    {"name": "Residence", "date": "2001", "value": "8.5"},
    {"name": "Clothing", "date": "2001", "value": "6.2"},
    {"name": "Household Facilities, Services", "date": "2001", "value": "6.2"},
    {"name": "Medicines", "date": "2001", "value": "6"},
    {"name": "Miscellanecus", "date": "2001", "value": "4.2"},
    {"name": "Food", "date": "2002", "value": "39.4"},
    {"name": "Education,Culture and Services", "date": "2002", "value": "15.9"},
    {"name": "Residence", "date": "2002", "value": "11.4"},
    {"name": "Traffic and Communication", "date": "2002", "value": "10.7"},
    {"name": "Medicines", "date": "2002", "value": "7"},
    {"name": "Household Facilities, Services", "date": "2002", "value": "6.2"},
    {"name": "Clothing", "date": "2002", "value": "5.9"},
    {"name": "Miscellanecus", "date": "2002", "value": "3.5"},
    {"name": "Food", "date": "2003", "value": "37.2"},
    {"name": "Education,Culture and Services", "date": "2003", "value": "16.6"},
    {"name": "Residence", "date": "2003", "value": "11.6"},
    {"name": "Traffic and Communication", "date": "2003", "value": "11.4"},
    {"name": "Household Facilities, Services", "date": "2003", "value": "7.2"},
    {"name": "Clothing", "date": "2003", "value": "6.8"},
    {"name": "Medicines", "date": "2003", "value": "5.4"},
    {"name": "Miscellanecus", "date": "2003", "value": "3.8"},
    {"name": "Food", "date": "2004", "value": "36.4"},
    {"name": "Education,Culture and Services", "date": "2004", "value": "17.4"},
    {"name": "Traffic and Communication", "date": "2004", "value": "13.5"},
    {"name": "Residence", "date": "2004", "value": "10.5"},
    {"name": "Clothing", "date": "2004", "value": "6.3"},
    {"name": "Household Facilities, Services", "date": "2004", "value": "6.2"},
    {"name": "Medicines", "date": "2004", "value": "6"},
    {"name": "Miscellanecus", "date": "2004", "value": "3.7"},
    {"name": "Food", "date": "2005", "value": "35.9"},
    {"name": "Education,Culture and Services", "date": "2005", "value": "16.5"},
    {"name": "Traffic and Communication", "date": "2005", "value": "14.4"},
    {"name": "Residence", "date": "2005", "value": "10.2"},
    {"name": "Clothing", "date": "2005", "value": "6.8"},
    {"name": "Household Facilities, Services", "date": "2005", "value": "5.8"},
    {"name": "Medicines", "date": "2005", "value": "5.8"},
    {"name": "Miscellanecus", "date": "2005", "value": "4.6"},
    {"name": "Food", "date": "2006", "value": "35.6"},
    {"name": "Education,Culture and Services", "date": "2006", "value": "16.5"},
    {"name": "Traffic and Communication", "date": "2006", "value": "15.8"},
    {"name": "Residence", "date": "2006", "value": "9.7"},
    {"name": "Clothing", "date": "2006", "value": "6.9"},
    {"name": "Household Facilities, Services", "date": "2006", "value": "5.9"},
    {"name": "Medicines", "date": "2006", "value": "5.2"},
    {"name": "Miscellanecus", "date": "2006", "value": "4.4"},
    {"name": "Food", "date": "2007", "value": "35.5"},
    {"name": "Traffic and Communication", "date": "2007", "value": "18.3"},
    {"name": "Education,Culture and Services", "date": "2007", "value": "15.4"},
    {"name": "Residence", "date": "2007", "value": "8.2"},
    {"name": "Clothing", "date": "2007", "value": "7.7"},
    {"name": "Household Facilities, Services", "date": "2007", "value": "5.5"},
    {"name": "Medicines", "date": "2007", "value": "5"},
    {"name": "Miscellanecus", "date": "2007", "value": "4.4"},
    {"name": "Food", "date": "2008", "value": "36.6"},
    {"name": "Traffic and Communication", "date": "2008", "value": "17.4"},
    {"name": "Education,Culture and Services", "date": "2008", "value": "14.8"},
    {"name": "Residence", "date": "2008", "value": "8.5"},
    {"name": "Clothing", "date": "2008", "value": "7.9"},
    {"name": "Household Facilities, Services", "date": "2008", "value": "6.1"},
    {"name": "Miscellanecus", "date": "2008", "value": "4.8"},
    {"name": "Medicines", "date": "2008", "value": "3.9"},
    {"name": "Food", "date": "2009", "value": "35"},
    {"name": "Traffic and Communication", "date": "2009", "value": "16.7"},
    {"name": "Education,Culture and Services", "date": "2009", "value": "14.9"},
    {"name": "Residence", "date": "2009", "value": "9.1"},
    {"name": "Clothing", "date": "2009", "value": "7.6"},
    {"name": "Household Facilities, Services", "date": "2009", "value": "6.5"},
    {"name": "Miscellanecus", "date": "2009", "value": "5.4"},
    {"name": "Medicines", "date": "2009", "value": "4.8"},
    {"name": "Food", "date": "2010", "value": "33.5"},
    {"name": "Traffic and Communication", "date": "2010", "value": "17.6"},
    {"name": "Education,Culture and Services", "date": "2010", "value": "14.5"},
    {"name": "Residence", "date": "2010", "value": "9.3"},
    {"name": "Household Facilities, Services", "date": "2010", "value": "7.8"},
    {"name": "Clothing", "date": "2010", "value": "7.7"},
    {"name": "Miscellanecus", "date": "2010", "value": "5.3"},
    {"name": "Medicines", "date": "2010", "value": "4.3"},
    {"name": "Food", "date": "2011", "value": "35.5"},
    {"name": "Traffic and Communication", "date": "2011", "value": "15.2"},
    {"name": "Education,Culture and Services", "date": "2011", "value": "14.9"},
    {"name": "Residence", "date": "2011", "value": "8.9"},
    {"name": "Clothing", "date": "2011", "value": "8.2"},
    {"name": "Household Facilities, Services", "date": "2011", "value": "7.3"},
    {"name": "Miscellanecus", "date": "2011", "value": "5.5"},
    {"name": "Medicines", "date": "2011", "value": "4.5"},
    {"name": "Food", "date": "2012", "value": "36.8"},
    {"name": "Traffic and Communication", "date": "2012", "value": "17.4"},
    {"name": "Education,Culture and Services", "date": "2012", "value": "14.2"},
    {"name": "Clothing", "date": "2012", "value": "8"},
    {"name": "Household Facilities, Services", "date": "2012", "value": "7.3"},
    {"name": "Residence", "date": "2012", "value": "6.8"},
    {"name": "Miscellanecus", "date": "2012", "value": "5.6"},
    {"name": "Medicines", "date": "2012", "value": "3.9"},
    {"name": "Food", "date": "2013", "value": "34.9"},
    {"name": "Traffic and Communication", "date": "2013", "value": "16.8"},
    {"name": "Education,Culture and Services", "date": "2013", "value": "14.6"},
    {"name": "Residence", "date": "2013", "value": "10.1"},
    {"name": "Clothing", "date": "2013", "value": "7.2"},
    {"name": "Household Facilities, Services", "date": "2013", "value": "6.1"},
    {"name": "Miscellanecus", "date": "2013", "value": "5.5"},
    {"name": "Medicines", "date": "2013", "value": "4.8"},
    {"name": "Food", "date": "2014", "value": "35"},
    {"name": "Education,Culture and Services", "date": "2014", "value": "16.2"},
    {"name": "Traffic and Communication", "date": "2014", "value": "16"},
    {"name": "Residence", "date": "2014", "value": "9.9"},
    {"name": "Clothing", "date": "2014", "value": "6.7"},
    {"name": "Household Facilities, Services", "date": "2014", "value": "5.8"},
    {"name": "Miscellanecus", "date": "2014", "value": "5.7"},
    {"name": "Medicines", "date": "2014", "value": "4.7"},
    {"name": "Residence", "date": "2015", "value": "32.8"},
    {"name": "Food", "date": "2015", "value": "26.2"},
    {"name": "Traffic and Communication", "date": "2015", "value": "12.1"},
    {"name": "Education,Culture and Services", "date": "2015", "value": "11"},
    {"name": "Medicines", "date": "2015", "value": "6.4"},
    {"name": "Clothing", "date": "2015", "value": "4.6"},
    {"name": "Household Facilities, Services", "date": "2015", "value": "4.3"},
    {"name": "Miscellanecus", "date": "2015", "value": "2.6"},
    {"name": "Residence", "date": "2016", "value": "33.2"},
    {"name": "Food", "date": "2016", "value": "25.1"},
    {"name": "Education,Culture and Services", "date": "2016", "value": "11.4"},
    {"name": "Traffic and Communication", "date": "2016", "value": "11.1"},
    {"name": "Medicines", "date": "2016", "value": "7.1"},
    {"name": "Household Facilities, Services", "date": "2016", "value": "4.7"},
    {"name": "Clothing", "date": "2016", "value": "4.6"},
    {"name": "Miscellanecus", "date": "2016", "value": "2.8"},
    {"name": "Residence", "date": "2017", "value": "34.9"},
    {"name": "Food", "date": "2017", "value": "24.7"},
    {"name": "Education,Culture and Services", "date": "2017", "value": "12"},
    {"name": "Traffic and Communication", "date": "2017", "value": "10"},
    {"name": "Medicines", "date": "2017", "value": "6.5"},
    {"name": "Household Facilities, Services", "date": "2017", "value": "4.6"},
    {"name": "Clothing", "date": "2017", "value": "4.3"},
    {"name": "Miscellanecus", "date": "2017", "value": "3"},
    {"name": "Residence", "date": "2018", "value": "33.4"},
    {"name": "Food", "date": "2018", "value": "24.1"},
    {"name": "Education,Culture and Services", "date": "2018", "value": "11.9"},
    {"name": "Traffic and Communication", "date": "2018", "value": "11.1"},
    {"name": "Medicines", "date": "2018", "value": "7"},
    {"name": "Household Facilities, Services", "date": "2018", "value": "4.8"},
    {"name": "Clothing", "date": "2018", "value": "4.7"},
    {"name": "Miscellanecus", "date": "2018", "value": "3"},
    {"name": "Residence", "date": "2019", "value": "33.7"},
    {"name": "Food", "date": "2019", "value": "23.3"},
    {"name": "Education,Culture and Services", "date": "2019", "value": "12.4"},
    {"name": "Traffic and Communication", "date": "2019", "value": "11.6"},
    {"name": "Medicines", "date": "2019", "value": "6.9"},
    {"name": "Household Facilities, Services", "date": "2019", "value": "4.6"},
    {"name": "Clothing", "date": "2019", "value": "4.5"},
    {"name": "Miscellanecus", "date": "2019", "value": "3"}]